# CMake script to convert a palette .bin into a C array.
# Usage: cmake -DPALETTE_BIN_FILE=palettes/clementina-text.palette.bin -DPALETTE_DATA_FILE=palette_data.c -P generate_palette_data.cmake
#
# The .palette.bin is the tile editor export format: 16 palette banks * 8
# little-endian RGB565 colors = 256 bytes. The video subsystem copies it
# verbatim into MIA video palette RAM at startup.

if(NOT PALETTE_BIN_FILE)
    message(FATAL_ERROR "PALETTE_BIN_FILE not specified")
endif()

if(NOT PALETTE_DATA_FILE)
    message(FATAL_ERROR "PALETTE_DATA_FILE not specified")
endif()

if(EXISTS ${PALETTE_BIN_FILE})
    file(READ ${PALETTE_BIN_FILE} PALETTE_BINARY_DATA HEX)
    file(SIZE ${PALETTE_BIN_FILE} PALETTE_SIZE)
else()
    message(FATAL_ERROR "Palette binary file ${PALETTE_BIN_FILE} not found")
endif()

if(NOT PALETTE_SIZE EQUAL 256)
    message(FATAL_ERROR "Palette binary file ${PALETTE_BIN_FILE} must be 256 bytes, got ${PALETTE_SIZE}")
endif()

string(LENGTH ${PALETTE_BINARY_DATA} HEX_LENGTH)
math(EXPR NUM_BYTES "${HEX_LENGTH} / 2")

set(C_ARRAY_DATA "")
set(BYTES_PER_LINE 16)
set(BYTE_COUNT 0)

foreach(i RANGE 1 ${NUM_BYTES})
    math(EXPR BYTE_INDEX "(${i} - 1) * 2")
    string(SUBSTRING ${PALETTE_BINARY_DATA} ${BYTE_INDEX} 2 HEX_BYTE)

    math(EXPR LINE_POS "${BYTE_COUNT} % ${BYTES_PER_LINE}")
    if(LINE_POS EQUAL 0)
        if(BYTE_COUNT GREATER 0)
            string(APPEND C_ARRAY_DATA "\n")
        endif()
        string(APPEND C_ARRAY_DATA "    ")
    endif()

    string(APPEND C_ARRAY_DATA "0x${HEX_BYTE}")
    math(EXPR NEXT_BYTE "${BYTE_COUNT} + 1")
    if(NEXT_BYTE LESS NUM_BYTES)
        string(APPEND C_ARRAY_DATA ", ")
    endif()

    math(EXPR BYTE_COUNT "${BYTE_COUNT} + 1")
endforeach()

file(WRITE ${PALETTE_DATA_FILE} "/**\n")
file(APPEND ${PALETTE_DATA_FILE} " * Generated palette data from ${PALETTE_BIN_FILE}\n")
file(APPEND ${PALETTE_DATA_FILE} " * This file is automatically generated during build - do not edit manually\n")
file(APPEND ${PALETTE_DATA_FILE} " */\n\n")
file(APPEND ${PALETTE_DATA_FILE} "#include <stdint.h>\n")
file(APPEND ${PALETTE_DATA_FILE} "#include <stddef.h>\n\n")
file(APPEND ${PALETTE_DATA_FILE} "// Palette image (${PALETTE_SIZE} bytes: 16 banks * 8 RGB565 colors)\n")
file(APPEND ${PALETTE_DATA_FILE} "const uint8_t mia_palette[] = {\n")
file(APPEND ${PALETTE_DATA_FILE} "${C_ARRAY_DATA}\n")
file(APPEND ${PALETTE_DATA_FILE} "};\n\n")
file(APPEND ${PALETTE_DATA_FILE} "const size_t mia_palette_size = ${PALETTE_SIZE};\n")

message(STATUS "Generated palette_data.c with ${PALETTE_SIZE} bytes from ${PALETTE_BIN_FILE}")
