# CMake script to convert kernel.bin to C array
# Usage: cmake -DKERNEL_BIN_FILE=kernel.bin -DKERNEL_DATA_FILE=kernel_data.c -P generate_kernel_data.cmake

if(NOT KERNEL_BIN_FILE)
    message(FATAL_ERROR "KERNEL_BIN_FILE not specified")
endif()

if(NOT KERNEL_DATA_FILE)
    message(FATAL_ERROR "KERNEL_DATA_FILE not specified")
endif()

# Read the binary file
if(EXISTS ${KERNEL_BIN_FILE})
    file(READ ${KERNEL_BIN_FILE} KERNEL_BINARY_DATA HEX)
    file(SIZE ${KERNEL_BIN_FILE} KERNEL_SIZE)
else()
    set(KERNEL_BINARY_DATA "")
    set(KERNEL_SIZE 0)
    message(WARNING "Kernel binary file ${KERNEL_BIN_FILE} not found, generating empty kernel data")
endif()

# Convert hex string to C array format
string(LENGTH ${KERNEL_BINARY_DATA} HEX_LENGTH)
set(C_ARRAY_DATA "")
set(BYTES_PER_LINE 16)
set(BYTE_COUNT 0)

if(HEX_LENGTH GREATER 0)
    math(EXPR NUM_BYTES "${HEX_LENGTH} / 2")
    
    # Process each byte
    foreach(i RANGE 0 ${NUM_BYTES})
        math(EXPR BYTE_INDEX "${i} * 2")
        if(BYTE_INDEX LESS HEX_LENGTH)
            string(SUBSTRING ${KERNEL_BINARY_DATA} ${BYTE_INDEX} 2 HEX_BYTE)
            
            # Add newline and indentation every 16 bytes
            math(EXPR LINE_POS "${BYTE_COUNT} % ${BYTES_PER_LINE}")
            if(LINE_POS EQUAL 0)
                if(BYTE_COUNT GREATER 0)
                    string(APPEND C_ARRAY_DATA "\n")
                endif()
                string(APPEND C_ARRAY_DATA "    ")
            endif()
            
            # Add the byte
            string(APPEND C_ARRAY_DATA "0x${HEX_BYTE}")
            
            # Add comma if not the last byte
            math(EXPR NEXT_BYTE "${BYTE_COUNT} + 1")
            if(NEXT_BYTE LESS NUM_BYTES)
                string(APPEND C_ARRAY_DATA ", ")
            endif()
            
            math(EXPR BYTE_COUNT "${BYTE_COUNT} + 1")
        endif()
    endforeach()
else()
    # Empty kernel - add a single zero byte to make valid C array
    set(C_ARRAY_DATA "    0x00")
endif()

# Write the C file header
file(WRITE ${KERNEL_DATA_FILE} "/**\n")
file(APPEND ${KERNEL_DATA_FILE} " * Generated kernel data from kernel.bin\n")
file(APPEND ${KERNEL_DATA_FILE} " * This file is automatically generated during build - do not edit manually\n")
file(APPEND ${KERNEL_DATA_FILE} " */\n\n")
file(APPEND ${KERNEL_DATA_FILE} "#include <stdint.h>\n")
file(APPEND ${KERNEL_DATA_FILE} "#include <stddef.h>\n\n")

# Write the array declaration
file(APPEND ${KERNEL_DATA_FILE} "// Kernel binary data (${KERNEL_SIZE} bytes)\n")
file(APPEND ${KERNEL_DATA_FILE} "const uint8_t kernel_data[] = {\n")
file(APPEND ${KERNEL_DATA_FILE} "${C_ARRAY_DATA}\n")
file(APPEND ${KERNEL_DATA_FILE} "};\n\n")

# Write the size declaration
file(APPEND ${KERNEL_DATA_FILE} "// Kernel size\n")
file(APPEND ${KERNEL_DATA_FILE} "const size_t kernel_data_size = ${KERNEL_SIZE};\n")

message(STATUS "Generated kernel_data.c with ${KERNEL_SIZE} bytes from ${KERNEL_BIN_FILE}")