#!/usr/bin/env python3
"""Generate src/mia/video/petscii_font.h from the MEGA65 open-roms charset.

The font is the MEGA65 "open-roms" character generator ROM: an independently
hand-drawn, PETSCII-compatible 8x8 character set (a clean-room, openly licensed
replacement for the Commodore 64 character ROM).

    Source : https://github.com/MEGA65/open-roms  (bin/chargen_openroms.rom)
    License: GNU LGPL v3.0 or later
    (c) Paul Gardner-Stephen 2019, Roman Standzikowski (FeralChild64) 2019-2021
    Full text: scripts/openroms-font-LICENSE.txt

Like the C64 ROM it replaces, it is 4096 bytes holding two 256-character sets
of 8x8 1bpp glyphs:

    block 1  (bytes    0-2047): uppercase / graphics set
    block 2  (bytes 2048-4095): lowercase / uppercase set

MIA stores CHR data as planar 1bpp bitplanes (256 chars * 8 rows = 2048 bytes
per plane). This maps:

    bank 0 plane 0  <- block 1  (uppercase / graphics)
    bank 0 plane 1  <- block 2  (lowercase / uppercase)

Pixel bit order differs between the two systems:

    charset ROM : bit 7 (MSB) is the leftmost pixel of a row
    MIA         : bit 0 (LSB) is the leftmost pixel of a row
                  (renderer reads (byte >> x) & 1, x = 0 at the left)

So every byte is bit-reversed here, at generation time, and the firmware can
then copy the planes straight into MIA RAM with no per-pixel work.

Usage:
    python3 scripts/generate_petscii_font.py [path-to-charset.rom]
"""

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_ROM = REPO_ROOT / "scripts" / "chargen_openroms.rom"
OUT_HEADER = REPO_ROOT / "src" / "mia" / "video" / "petscii_font.h"

PLANE_SIZE = 2048  # 256 chars * 8 rows


def reverse_bits(value: int) -> int:
    result = 0
    for i in range(8):
        result |= ((value >> i) & 1) << (7 - i)
    return result


REVERSE_TABLE = [reverse_bits(b) for b in range(256)]


def emit_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}[{PLANE_SIZE}] = {{"]
    for row in range(0, len(data), 12):
        chunk = data[row:row + 12]
        lines.append("    " + " ".join(f"0x{b:02X}," for b in chunk))
    lines.append("};")
    return "\n".join(lines)


def ascii_preview(plane: bytes, char: int) -> str:
    """Render one glyph in MIA pixel order (LSB = left) for a sanity check."""
    rows = []
    for y in range(8):
        byte = plane[char * 8 + y]
        rows.append("".join("#" if (byte >> x) & 1 else "." for x in range(8)))
    return "\n".join(rows)


def main() -> int:
    rom_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_ROM
    rom = rom_path.read_bytes()
    if len(rom) != 4096:
        print(f"error: expected a 4096-byte charset, got {len(rom)} bytes from {rom_path}",
              file=sys.stderr)
        return 1

    plane0 = bytes(REVERSE_TABLE[b] for b in rom[0:PLANE_SIZE])              # uppercase set
    plane1 = bytes(REVERSE_TABLE[b] for b in rom[PLANE_SIZE:2 * PLANE_SIZE])  # lowercase set

    header = f"""\
/*
 * petscii_font.h - PETSCII-compatible font for MIA CHR bank 0.
 *
 * GENERATED by scripts/generate_petscii_font.py from the MEGA65 open-roms
 * character set. Do not edit by hand; re-run the generator instead.
 *
 * Font source : https://github.com/MEGA65/open-roms (bin/chargen_openroms.rom)
 * Font license: GNU LGPL v3.0 or later
 *   (c) Paul Gardner-Stephen 2019, Roman Standzikowski (FeralChild64) 2019-2021
 *   Full text in scripts/openroms-font-LICENSE.txt
 *
 *   mia_petscii_font_plane0  -> bank 0 plane 0 : uppercase / graphics set
 *   mia_petscii_font_plane1  -> bank 0 plane 1 : lowercase / uppercase set
 *
 * Bytes are pre-reversed to MIA pixel order (bit 0 = leftmost pixel).
 */
#ifndef _MIA_PETSCII_FONT_H_
#define _MIA_PETSCII_FONT_H_

#include <stdint.h>

#define MIA_PETSCII_FONT_PLANE_SIZE {PLANE_SIZE}u

{emit_array("mia_petscii_font_plane0", plane0)}

{emit_array("mia_petscii_font_plane1", plane1)}

#endif /* _MIA_PETSCII_FONT_H_ */
"""

    OUT_HEADER.write_text(header)
    print(f"wrote {OUT_HEADER} ({OUT_HEADER.stat().st_size} bytes)")
    print("\nplane 1 (lowercase set) char 'a' (screen code 1):")
    print(ascii_preview(plane1, 1))
    print("\nplane 0 (uppercase set) char 'A' (screen code 1):")
    print(ascii_preview(plane0, 1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
