# CMake script to convert a charset .bin into a C array.
# Usage: cmake -DCHARSET_BIN_FILE=openroms.bin -DCHARSET_DATA_FILE=charset_data.c -P generate_charset_data.cmake
#
# The .bin is a raw charset image in MIA pixel order. This script just embeds the
# bytes verbatim as mia_charset[] / mia_charset_size; video_load_default_font picks
# the layout at runtime by size: a multiple of a full 6144-byte CHR bank (3 planes)
# is a flat CHR dump loaded flat (clascii, the tile-editor "all banks" export),
# otherwise it is a sequence of 2048-byte plane-0 blocks, block i -> plane 0 of CHR
# bank i (openroms). The file's true length drives mia_charset_size.

if(NOT CHARSET_BIN_FILE)
    message(FATAL_ERROR "CHARSET_BIN_FILE not specified")
endif()

if(NOT CHARSET_DATA_FILE)
    message(FATAL_ERROR "CHARSET_DATA_FILE not specified")
endif()

if(EXISTS ${CHARSET_BIN_FILE})
    file(READ ${CHARSET_BIN_FILE} CHARSET_BINARY_DATA HEX)
    file(SIZE ${CHARSET_BIN_FILE} CHARSET_SIZE)
else()
    message(FATAL_ERROR "Charset binary file ${CHARSET_BIN_FILE} not found")
endif()

string(LENGTH ${CHARSET_BINARY_DATA} HEX_LENGTH)
math(EXPR NUM_BYTES "${HEX_LENGTH} / 2")

set(C_ARRAY_DATA "")
set(BYTES_PER_LINE 16)
set(BYTE_COUNT 0)

foreach(i RANGE 1 ${NUM_BYTES})
    math(EXPR BYTE_INDEX "(${i} - 1) * 2")
    string(SUBSTRING ${CHARSET_BINARY_DATA} ${BYTE_INDEX} 2 HEX_BYTE)

    math(EXPR LINE_POS "${BYTE_COUNT} % ${BYTES_PER_LINE}")
    if(LINE_POS EQUAL 0)
        if(BYTE_COUNT GREATER 0)
            string(APPEND C_ARRAY_DATA "\n")
        endif()
        string(APPEND C_ARRAY_DATA "    ")
    endif()

    string(APPEND C_ARRAY_DATA "0x${HEX_BYTE}")
    math(EXPR NEXT_BYTE "${BYTE_COUNT} + 1")
    if(NEXT_BYTE LESS NUM_BYTES)
        string(APPEND C_ARRAY_DATA ", ")
    endif()

    math(EXPR BYTE_COUNT "${BYTE_COUNT} + 1")
endforeach()

file(WRITE ${CHARSET_DATA_FILE} "/**\n")
file(APPEND ${CHARSET_DATA_FILE} " * Generated charset data from ${CHARSET_BIN_FILE}\n")
file(APPEND ${CHARSET_DATA_FILE} " * This file is automatically generated during build - do not edit manually\n")
file(APPEND ${CHARSET_DATA_FILE} " */\n\n")
file(APPEND ${CHARSET_DATA_FILE} "#include <stdint.h>\n")
file(APPEND ${CHARSET_DATA_FILE} "#include <stddef.h>\n\n")
file(APPEND ${CHARSET_DATA_FILE} "// Charset image (${CHARSET_SIZE} bytes: 2048-byte blocks, block i -> CHR bank i plane 0)\n")
file(APPEND ${CHARSET_DATA_FILE} "const uint8_t mia_charset[] = {\n")
file(APPEND ${CHARSET_DATA_FILE} "${C_ARRAY_DATA}\n")
file(APPEND ${CHARSET_DATA_FILE} "};\n\n")
file(APPEND ${CHARSET_DATA_FILE} "const size_t mia_charset_size = ${CHARSET_SIZE};\n")

message(STATUS "Generated charset_data.c with ${CHARSET_SIZE} bytes from ${CHARSET_BIN_FILE}")
